#ifndef GATEWAY_COMMANDS_H
#define GATEWAY_COMMANDS_H

#include <stdint.h>
#include "motor_service.h"

/* 上游网关命令寄存器地址。 */
typedef enum {
    GATEWAY_CMD_OPEN_DOOR = 0x0030U,
    GATEWAY_CMD_CLOSE_DOOR = 0x0031U,
    GATEWAY_CMD_CLOSE_CENTER = 0x0032U,
    GATEWAY_CMD_LEAVE_CENTER = 0x0033U,
    GATEWAY_CMD_LIFT_UP = 0x0034U,
    GATEWAY_CMD_LIFT_DOWN = 0x0035U,
    GATEWAY_CMD_LOAD_BATTERY = 0x0036U,
    GATEWAY_CMD_UNLOAD_BATTERY = 0x0037U,
    GATEWAY_CMD_TAKEOFF = 0x0038U,
    GATEWAY_CMD_OPEN_DOOR_ALT = 0x0039U,
    GATEWAY_CMD_LANDING = 0x0040U,
    GATEWAY_CMD_PAUSE = 0x0041U,
    GATEWAY_CMD_RESUME = 0x0042U,
    GATEWAY_CMD_CANCEL = 0x0043U,
    GATEWAY_CMD_OPEN_UP = 0x0044U,
    GATEWAY_CMD_CLOSE_DOWN = 0x0045U,
    GATEWAY_CMD_CHARGER_ON = 0x0048U,
    GATEWAY_CMD_CHARGER_OFF = 0x0049U,
    GATEWAY_CMD_OPEN_FLY = 0x0050U,
    GATEWAY_CMD_CLOSE_FLY = 0x0051U,
    GATEWAY_CMD_UAV_POWER_ON = 0x0052U,
    GATEWAY_CMD_UAV_POWER_MODE2 = 0x0053U,
    GATEWAY_CMD_COOLING_STOP_TEMP = 0x0054U,
    GATEWAY_CMD_HEATING_STOP_TEMP = 0x0055U,
    GATEWAY_CMD_UAV_STATUS = 0x0060U
} GatewayCommandRegister;

typedef struct {
    MotorServiceTarget target;
} GatewayCommandTarget;

/* 查询需要直接转发到下游设备的普通命令；找到时返回 1。 */
uint8_t GatewayCommands_FindTarget(uint16_t gateway_register,
                                   GatewayCommandTarget *target);

#endif
